name: vision_football
description: AR penalty kick football game using ML Kit pose detection and Flame.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_mlkit_pose_detection: ^0.14.1
  camera: ^0.12.0+1
  flame: ^1.37.0
  sensors_plus: ^7.0.0
  vector_math: ^2.2.0
  app_settings: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/goal_post.png
    - assets/images/stadium_crowd.png
    - assets/images/Football-fans.gif
    - assets/images/football_boot_right.png
    - assets/images/shoe/top-right-shoe.png
    - assets/images/keeper/Keeper-front.png
    - assets/images/keeper/Keeper-left.png
    - assets/images/keeper/Keeper-right.png
    - assets/images/keeper/Keeper-top-left.png
    - assets/images/keeper/Keeper-top-right.png
    - assets/images/keeper/Keeper-crouch-left.png
    - assets/images/keeper/Keeper-crouch-right.png
    - assets/images/keeper/Keeper-straight-top.png
    - assets/images/keeper/Keeper-recovery-left.png
    - assets/images/keeper/Keeper-recovery-right.png
    - assets/images/keeper/gloves/Keeper-glove-left.png
    - assets/images/keeper/gloves/Keeper-glove-right.png
    - assets/goal/Inside-goal.png
    - assets/images/ball/Ball-left.png
    - assets/images/ball/Ball-right.png
    - assets/images/shooter/Player-IdlePosition.png
    - assets/images/shooter/Player-Right-RunUp.png
    - assets/images/shooter/Player-Left-RunUp.png
    - assets/images/shooter/Player-Backswing.png
    - assets/images/shooter/Player-Impact.png
    - assets/images/shooter/Player-FollowThrough.png
    - assets/images/shooter/Player-Recovery.png
    - assets/images/outlines/upperbody-outline.png
    - assets/images/outlines/lowerbody-outline.png
    - assets/images/stadium/stadium-keeper-view.png
    - assets/images/logo.png
    - assets/images/VisionFootball-Logo-NoBG.png
    - assets/images/main_page/stadium_bg.jpeg
    - assets/images/main_page/match_art.png
    - assets/images/main_page/tournament_art.png
    - assets/images/main_page/online_art.jpeg
    - assets/images/main_page/avatars/avatar_1.png
    - assets/images/main_page/avatars/avatar_2.png
    - assets/images/main_page/avatars/avatar_3.png
    - assets/images/main_page/avatars/avatar_4.png
